const CONFIRM_NEW_PASSWORD_RESET = "CONFIRM_NEW_PASSWORD_RESET";

const ACTION_CONFIRM_NEW_PASSWORD_RESET = () => {
  return {
    type: CONFIRM_NEW_PASSWORD_RESET,
  };
};

export default ACTION_CONFIRM_NEW_PASSWORD_RESET;
