const NEW_PASSWORD_NOT_VALID = "NEW_PASSWORD_NOT_VALID";

const ACTION_NEW_PASSWORD_NOT_VALID = () => {
  return {
    type: NEW_PASSWORD_NOT_VALID,
  };
};

export default ACTION_NEW_PASSWORD_NOT_VALID;
