const IS_ECOMMERCE_MEETNOW_NOT_ACTIVE = "IS_ECOMMERCE_MEETNOW_NOT_ACTIVE";

const ACTION_IS_ECOMMERCE_MEETNOW_NOT_ACTIVE = () => {
  return {
    type: IS_ECOMMERCE_MEETNOW_NOT_ACTIVE
  };
};

export default ACTION_IS_ECOMMERCE_MEETNOW_NOT_ACTIVE;
