const IS_ECOMMERCEPAGE_NOT_ACTIVE = "IS_ECOMMERCEPAGE_NOT_ACTIVE";

const ACTION_IS_ECOMMERCEPAGE_NOT_ACTIVE = () => {
  return {
    type: IS_ECOMMERCEPAGE_NOT_ACTIVE
  };
};

export default ACTION_IS_ECOMMERCEPAGE_NOT_ACTIVE;
