const IS_ECOMMERCEPAGE_ACTIVE = "IS_ECOMMERCEPAGE_ACTIVE";

const ACTION_IS_ECOMMERCEPAGE_ACTIVE = () => {
  return {
    type: IS_ECOMMERCEPAGE_ACTIVE
  };
};

export default ACTION_IS_ECOMMERCEPAGE_ACTIVE;
