const IS_ECOMMERCE_MEETNOW_ACTIVE = "IS_ECOMMERCE_MEETNOW_ACTIVE";

const ACTION_IS_ECOMMERCE_MEETNOW_ACTIVE = () => {
  return {
    type: IS_ECOMMERCE_MEETNOW_ACTIVE
  };
};

export default ACTION_IS_ECOMMERCE_MEETNOW_ACTIVE;
