const NEW_PASSWORD_NOT_INVALID = "NEW_PASSWORD_NOT_INVALID";

const ACTION_NEW_PASSWORD_NOT_INVALID = () => {
  return {
    type: NEW_PASSWORD_NOT_INVALID,
  };
};

export default ACTION_NEW_PASSWORD_NOT_INVALID;
