const DUMMY_TEMPORARY_TOKEN_RESET = "DUMMY_TEMPORARY_TOKEN_RESET";

const ACTION_DUMMY_TEMPORARY_TOKEN_RESET = () => {
  return {
    type: DUMMY_TEMPORARY_TOKEN_RESET,
  };
};

export default ACTION_DUMMY_TEMPORARY_TOKEN_RESET;
