const ON_UPCOMING_PAGE_RESET = "ON_UPCOMING_PAGE_RESET";

const ACTION_ON_UPCOMING_PAGE_RESET = () => {
  return {
    type: ON_UPCOMING_PAGE_RESET,
  };
};

export default ACTION_ON_UPCOMING_PAGE_RESET;
