const ON_CHECKEDIN_UPDATE_RESET = "ON_CHECKEDIN_UPDATE_RESET";

const ACTION_ON_CHECKEDIN_UPDATE_RESET = () => {
  return {
    type: ON_CHECKEDIN_UPDATE_RESET,
  };
};

export default ACTION_ON_CHECKEDIN_UPDATE_RESET;
