const CONFIRM_NEW_PASSWORD_VALID = "CONFIRM_NEW_PASSWORD_VALID";

const ACTION_CONFIRM_NEW_PASSWORD_VALID = () => {
  return {
    type: CONFIRM_NEW_PASSWORD_VALID,
  };
};

export default ACTION_CONFIRM_NEW_PASSWORD_VALID;
