const CONFIRM_NEW_PASSWORD_INVALID = "CONFIRM_NEW_PASSWORD_INVALID";

const ACTION_CONFIRM_NEW_PASSWORD_INVALID = () => {
  return {
    type: CONFIRM_NEW_PASSWORD_INVALID,
  };
};

export default ACTION_CONFIRM_NEW_PASSWORD_INVALID;
